apiVersion: v2
name: webrix-postgres
description: PostgreSQL Helm chart using the official Docker image
type: application
version: 1.0.0
appVersion: "17.4"
keywords:
  - postgresql
  - postgres
  - database
home: https://www.postgresql.org/
sources:
  - https://github.com/docker-library/postgres
maintainers:
  - name: Webrix
