{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with (include "postgresql.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.enablePostgresUser }}
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.username }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
